In [1]:
from tslearn.utils import to_time_series_dataset

In [2]:
X = to_time_series_dataset([[1, 2, 3, 4], [1, 2, 3], [2, 5, 6, 7, 8, 9]])

In [3]:
y = [0, 0, 1]

In [4]:
X

array([[[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [nan],
        [nan]],

       [[ 1.],
        [ 2.],
        [ 3.],
        [nan],
        [nan],
        [nan]],

       [[ 2.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]]])

In [5]:
y

[0, 0, 1]

In [6]:
from tslearn.clustering import GlobalAlignmentKernelKMeans

In [7]:
gak_km = GlobalAlignmentKernelKMeans(n_clusters=2)

In [8]:
labels_gak = gak_km.fit_predict(X)

Resumed because of empty cluster
2.000 --> 2.000 --> 


In [9]:
labels_gak

array([1, 0, 1])

In [10]:
from tslearn.clustering import TimeSeriesKMeans

In [11]:
km = TimeSeriesKMeans(n_clusters=2, metric="dtw")

In [12]:
labels = km.fit_predict(X)

Resumed because of empty cluster
Resumed because of empty cluster
Resumed because of empty cluster
5.000 --> 1.056 --> 1.056 --> 


In [13]:
labels

array([1, 1, 0])

In [14]:
km_bis = TimeSeriesKMeans(n_clusters=2, metric="softdtw")

In [15]:
labels_bis = km_bis.fit_predict(X)

Resumed because of empty cluster
Resumed because of empty cluster
Resumed because of empty cluster
Resumed because of empty cluster
Resumed because of empty cluster
Resumed because of empty cluster
58.996 --> 1.956 --> 1.956 --> 1.956 --> 1.956 --> 


In [16]:
from tslearn.clustering import TimeSeriesKMeans, silhouette_score

In [17]:
km = TimeSeriesKMeans(n_clusters=2, metric="dtw")

In [18]:
labels = km.fit_predict(X)

5.000 --> 1.056 --> 1.056 --> 


In [19]:
labels 

array([1, 1, 0])

In [20]:
silhouette_score(X, labels, metric="dtw")

0.5875727602071013

In [21]:
from tslearn.barycenters import dtw_barycenter_averaging

In [22]:
bar = dtw_barycenter_averaging(X, barycenter_size=3)

In [23]:
from tslearn.barycenters import softdtw_barycenter

In [24]:
from tslearn.utils import ts_zeros

In [25]:
initial_barycenter = ts_zeros(sz=5)

In [26]:
bar = softdtw_barycenter(X, init=initial_barycenter)